/* ========================================
   2026 World Cup Data - REAL DATA FROM FIFA API
   Updated: June 12, 2026
   ======================================== */
window.__WC_DATA = {
  groups: {
    A: { name: 'A组', teams: ['Mexico','SouthAfrica','SouthKorea','Czechia'] },
    B: { name: 'B组', teams: ['Canada','Bosnia','Qatar','Switzerland'] },
    C: { name: 'C组', teams: ['Brazil','Morocco','Haiti','Scotland'] },
    D: { name: 'D组', teams: ['USA','Paraguay','Australia','Turkiye'] },
    E: { name: 'E组', teams: ['Germany','Curacao','IvoryCoast','Ecuador'] },
    F: { name: 'F组', teams: ['Netherlands','Japan','Sweden','Tunisia'] },
    G: { name: 'G组', teams: ['Belgium','Egypt','Iran','NewZealand'] },
    H: { name: 'H组', teams: ['Spain','CaboVerde','SaudiArabia','Uruguay'] },
    I: { name: 'I组', teams: ['France','Senegal','Iraq','Norway'] },
    J: { name: 'J组', teams: ['Argentina','Algeria','Austria','Jordan'] },
    K: { name: 'K组', teams: ['Portugal','CongoDR','Uzbekistan','Colombia'] },
    L: { name: 'L组', teams: ['England','Croatia','Ghana','Panama'] }
  },
  matchResults: {},
  teams: {
    Mexico:       { name:'墨西哥', flag:'🇲🇽', rank:12, color:'#006847' },
    SouthAfrica:  { name:'南非', flag:'🇿🇦', rank:66, color:'#FFB81C' },
    SouthKorea:   { name:'韩国', flag:'🇰🇷', rank:26, color:'#C60C30' },
    Czechia:      { name:'捷克', flag:'🇨🇿', rank:31, color:'#11457E' },
    Canada:       { name:'加拿大', flag:'🇨🇦', rank:49, color:'#E0115F' },
    Bosnia:       { name:'波黑', flag:'🇧🇦', rank:62, color:'#001B3A' },
    Qatar:        { name:'卡塔尔', flag:'🇶🇦', rank:58, color:'#8D1B3D' },
    Switzerland:  { name:'瑞士', flag:'🇨🇭', rank:15, color:'#DA291C' },
    Brazil:       { name:'巴西', flag:'🇧🇷', rank:5, color:'#009739' },
    Morocco:      { name:'摩洛哥', flag:'🇲🇦', rank:13, color:'#C1272D' },
    Haiti:        { name:'海地', flag:'🇭🇹', rank:86, color:'#00209F' },
    Scotland:     { name:'苏格兰', flag:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', rank:38, color:'#005EB8' },
    USA:          { name:'美国', flag:'🇺🇸', rank:11, color:'#3C3B6E' },
    Paraguay:     { name:'巴拉圭', flag:'🇵🇾', rank:51, color:'#0038A8' },
    Australia:    { name:'澳大利亚', flag:'🇦🇺', rank:39, color:'#FFD700' },
    Turkiye:      { name:'土耳其', flag:'🇹🇷', rank:29, color:'#E30A17' },
    Germany:      { name:'德国', flag:'🇩🇪', rank:10, color:'#000000' },
    Curacao:      { name:'库拉索', flag:'🇨🇼', rank:90, color:'#002B7F' },
    IvoryCoast:   { name:'科特迪瓦', flag:'🇨🇮', rank:41, color:'#F77F00' },
    Ecuador:      { name:'厄瓜多尔', flag:'🇪🇨', rank:36, color:'#FFE600' },
    Netherlands:  { name:'荷兰', flag:'🇳🇱', rank:3, color:'#FF6600' },
    Japan:        { name:'日本', flag:'🇯🇵', rank:18, color:'#BC002D' },
    Sweden:       { name:'瑞典', flag:'🇸🇪', rank:27, color:'#FFB300' },
    Tunisia:      { name:'突尼斯', flag:'🇹🇳', rank:30, color:'#E70013' },
    Belgium:      { name:'比利时', flag:'🇧🇪', rank:6, color:'#FFE62E' },
    Egypt:        { name:'埃及', flag:'🇪🇬', rank:34, color:'#C8102E' },
    Iran:         { name:'伊朗', flag:'🇮🇷', rank:22, color:'#239F40' },
    NewZealand:   { name:'新西兰', flag:'🇳🇿', rank:94, color:'#000000' },
    Spain:        { name:'西班牙', flag:'🇪🇸', rank:8, color:'#C60B1E' },
    CaboVerde:    { name:'佛得角', flag:'🇨🇻', rank:72, color:'#003893' },
    SaudiArabia:  { name:'沙特阿拉伯', flag:'🇸🇦', rank:56, color:'#006C35' },
    Uruguay:      { name:'乌拉圭', flag:'🇺🇾', rank:14, color:'#0038A8' },
    France:       { name:'法国', flag:'🇫🇷', rank:2, color:'#002395' },
    Senegal:      { name:'塞内加尔', flag:'🇸🇳', rank:20, color:'#00853F' },
    Iraq:         { name:'伊拉克', flag:'🇮🇶', rank:67, color:'#007A3D' },
    Norway:       { name:'挪威', flag:'🇳🇴', rank:23, color:'#BA0C2F' },
    Argentina:    { name:'阿根廷', flag:'🇦🇷', rank:1, color:'#75AADB' },
    Algeria:      { name:'阿尔及利亚', flag:'🇩🇿', rank:43, color:'#006633' },
    Austria:      { name:'奥地利', flag:'🇦🇹', rank:25, color:'#ED2939' },
    Jordan:       { name:'约旦', flag:'🇯🇴', rank:70, color:'#000000' },
    Portugal:     { name:'葡萄牙', flag:'🇵🇹', rank:7, color:'#006600' },
    CongoDR:      { name:'刚果(金)', flag:'🇨🇩', rank:65, color:'#007FFF' },
    Uzbekistan:   { name:'乌兹别克斯坦', flag:'🇺🇿', rank:74, color:'#1EB53A' },
    Colombia:     { name:'哥伦比亚', flag:'🇨🇴', rank:17, color:'#FCD116' },
    England:      { name:'英格兰', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', rank:4, color:'#CF081F' },
    Croatia:      { name:'克罗地亚', flag:'🇭🇷', rank:9, color:'#C8102E' },
    Ghana:        { name:'加纳', flag:'🇬🇭', rank:60, color:'#006633' },
    Panama:       { name:'巴拿马', flag:'🇵🇦', rank:55, color:'#00529F' }
  },
  teamStrength: {
    Argentina:    { overall:94, attack:92, defense:88 },
    France:       { overall:93, attack:94, defense:85 },
    Brazil:       { overall:92, attack:93, defense:83 },
    England:      { overall:90, attack:88, defense:85 },
    Spain:        { overall:89, attack:87, defense:84 },
    Portugal:     { overall:88, attack:86, defense:83 },
    Netherlands:  { overall:87, attack:85, defense:84 },
    Germany:      { overall:87, attack:85, defense:86 },
    Belgium:      { overall:86, attack:84, defense:81 },
    Croatia:      { overall:83, attack:80, defense:82 },
    Uruguay:      { overall:81, attack:79, defense:80 },
    Colombia:     { overall:80, attack:78, defense:77 },
    Morocco:      { overall:80, attack:76, defense:82 },
    Japan:        { overall:78, attack:76, defense:77 },
    Switzerland:  { overall:78, attack:74, defense:80 },
    Mexico:       { overall:77, attack:75, defense:76 },
    USA:          { overall:76, attack:75, defense:74 },
    Senegal:      { overall:76, attack:74, defense:75 },
    Iran:         { overall:74, attack:72, defense:75 },
    SouthKorea:   { overall:74, attack:73, defense:72 },
    Sweden:       { overall:72, attack:70, defense:73 },
    Norway:       { overall:72, attack:72, defense:70 },
    Ecuador:      { overall:70, attack:70, defense:68 },
    Australia:    { overall:70, attack:68, defense:70 },
    Egypt:        { overall:68, attack:68, defense:66 },
    Tunisia:      { overall:68, attack:66, defense:70 },
    SaudiArabia:  { overall:63, attack:63, defense:62 },
    Canada:       { overall:62, attack:61, defense:62 },
    Ghana:        { overall:65, attack:66, defense:62 },
    Paraguay:     { overall:64, attack:62, defense:66 },
    Qatar:        { overall:58, attack:57, defense:59 },
    Panama:       { overall:57, attack:56, defense:57 },
    NewZealand:   { overall:54, attack:52, defense:56 },
    Iraq:         { overall:56, attack:56, defense:55 },
    Algeria:      { overall:69, attack:69, defense:67 },
    Austria:      { overall:71, attack:70, defense:71 },
    Scotland:     { overall:68, attack:67, defense:67 },
    Turkiye:      { overall:69, attack:70, defense:66 },
    Czechia:      { overall:67, attack:66, defense:67 },
    SouthAfrica:  { overall:61, attack:60, defense:61 },
    Bosnia:       { overall:63, attack:62, defense:62 },
    Haiti:        { overall:52, attack:51, defense:53 },
    Curacao:      { overall:50, attack:49, defense:51 },
    IvoryCoast:   { overall:69, attack:68, defense:67 },
    CaboVerde:    { overall:59, attack:58, defense:59 },
    Jordan:       { overall:57, attack:56, defense:57 },
    CongoDR:      { overall:62, attack:62, defense:60 },
    Uzbekistan:   { overall:60, attack:59, defense:60 }
  },
  wcHistory: {
    Argentina: { apps:18, best:'冠军', bestYear:2022, last3Wc:[2,16,1], sfCount:6 },
    France:    { apps:16, best:'冠军', bestYear:2018, last3Wc:[1,8,1], sfCount:7 },
    Brazil:    { apps:22, best:'冠军', bestYear:2002, last3Wc:[4,8,4], sfCount:11 },
    England:   { apps:16, best:'冠军', bestYear:1966, last3Wc:[4,4,2], sfCount:4 },
    Spain:     { apps:16, best:'冠军', bestYear:2010, last3Wc:[16,8,16], sfCount:3 },
    Portugal:  { apps:8,  best:'季军', bestYear:1966, last3Wc:[16,4,8], sfCount:2 },
    Netherlands:{ apps:11, best:'亚军', bestYear:2010, last3Wc:[3,8,null], sfCount:5 },
    Germany:   { apps:20, best:'冠军', bestYear:2014, last3Wc:[1,16,8], sfCount:13 },
    Belgium:   { apps:14, best:'季军', bestYear:2018, last3Wc:[3,8,16], sfCount:2 },
    Croatia:   { apps:6,  best:'亚军', bestYear:2018, last3Wc:[2,3,16], sfCount:3 },
    Uruguay:   { apps:14, best:'冠军', bestYear:1950, last3Wc:[4,8,16], sfCount:5 },
    Colombia:  { apps:6,  best:'8强',  bestYear:2014, last3Wc:[8,16,null], sfCount:0 },
    Morocco:   { apps:6,  best:'4强',  bestYear:2022, last3Wc:[16,16,4], sfCount:1 },
    Japan:     { apps:7,  best:'16强', bestYear:2018, last3Wc:[16,16,8], sfCount:0 },
    Switzerland:{ apps:12, best:'8强', bestYear:1954, last3Wc:[16,8,16], sfCount:0 },
    Mexico:    { apps:17, best:'8强', bestYear:1986, last3Wc:[16,16,8], sfCount:0 },
    USA:       { apps:11, best:'8强', bestYear:2002, last3Wc:[16,16,8], sfCount:0 },
    Senegal:   { apps:3,  best:'8强',  bestYear:2022, last3Wc:[8,null,16], sfCount:0 },
    Iran:      { apps:6,  best:'16强', bestYear:2022, last3Wc:[16,16,8], sfCount:0 },
    SouthKorea:{ apps:11, best:'4强',  bestYear:2002, last3Wc:[8,16,16], sfCount:1 },
    Sweden:    { apps:12, best:'亚军', bestYear:1958, last3Wc:[8,8,null], sfCount:3 },
    Australia: { apps:6,  best:'16强', bestYear:2006, last3Wc:[16,16,8], sfCount:0 },
    Ecuador:   { apps:4,  best:'16强', bestYear:2006, last3Wc:[16,8,null], sfCount:0 },
    Tunisia:   { apps:6,  best:'16强', bestYear:1978, last3Wc:[16,8,16], sfCount:0 },
    Egypt:     { apps:3,  best:'16强', bestYear:2002, last3Wc:[8,null,16], sfCount:0 },
    Ghana:     { apps:4,  best:'8强',  bestYear:2010, last3Wc:[8,16,16], sfCount:0 },
    Paraguay:  { apps:8,  best:'8强',  bestYear:2010, last3Wc:[8,null,null], sfCount:0 },
    SaudiArabia:{ apps:6, best:'16强', bestYear:1994, last3Wc:[16,8,16], sfCount:0 },
    Canada:    { apps:2,  best:'16强', bestYear:1986, last3Wc:[16,null,null], sfCount:0 },
    Qatar:     { apps:1,  best:'小组赛', bestYear:2022, last3Wc:[16,null,null], sfCount:0 },
    Panama:    { apps:1,  best:'小组赛', bestYear:2018, last3Wc:[16,null,null], sfCount:0 },
    NewZealand:{ apps:2,  best:'小组赛', bestYear:2010, last3Wc:[16,null,null], sfCount:0 },
    Iraq:      { apps:1,  best:'小组赛', bestYear:1986, last3Wc:[null,null,null], sfCount:0 },
    Algeria:   { apps:4,  best:'16强', bestYear:2014, last3Wc:[16,8,null], sfCount:0 },
    Norway:    { apps:3,  best:'16强', bestYear:1998, last3Wc:[null,null,null], sfCount:0 },
    Scotland:  { apps:8,  best:'16强', bestYear:1998, last3Wc:[null,null,null], sfCount:0 },
    Turkiye:   { apps:2,  best:'季军', bestYear:2002, last3Wc:[16,null,null], sfCount:1 },
    Czechia:   { apps:9,  best:'亚军', bestYear:1934, last3Wc:[16,8,null], sfCount:2 },
    SouthAfrica:{ apps:3, best:'小组赛', bestYear:2010, last3Wc:[16,null,null], sfCount:0 },
    Austria:   { apps:7,  best:'季军', bestYear:1954, last3Wc:[null,null,null], sfCount:1 },
    IvoryCoast:{ apps:3,  best:'小组赛', bestYear:2014, last3Wc:[16,null,null], sfCount:0 },
    Bosnia:    { apps:1,  best:'小组赛', bestYear:2014, last3Wc:[16,null,null], sfCount:0 },
    Haiti:     { apps:1,  best:'小组赛', bestYear:1974, last3Wc:[null,null,null], sfCount:0 },
    Curacao:   { apps:0,  best:'首秀', bestYear:null, last3Wc:[null,null,null], sfCount:0 },
    CaboVerde: { apps:0,  best:'首秀', bestYear:null, last3Wc:[null,null,null], sfCount:0 },
    Jordan:    { apps:0,  best:'首秀', bestYear:null, last3Wc:[null,null,null], sfCount:0 },
    CongoDR:   { apps:1,  best:'小组赛', bestYear:1974, last3Wc:[null,null,null], sfCount:0 },
    Uzbekistan:{ apps:0,  best:'首秀', bestYear:null, last3Wc:[null,null,null], sfCount:0 }
  },
  history: [
    { year:1930, host:'乌拉圭', winner:'乌拉圭', runnerUp:'阿根廷', score:'4-2' },
    { year:1934, host:'意大利', winner:'意大利', runnerUp:'捷克斯洛伐克', score:'2-1' },
    { year:1938, host:'法国', winner:'意大利', runnerUp:'匈牙利', score:'4-2' },
    { year:1950, host:'巴西', winner:'乌拉圭', runnerUp:'巴西', score:'2-1' },
    { year:1954, host:'瑞士', winner:'西德', runnerUp:'匈牙利', score:'3-2' },
    { year:1958, host:'瑞典', winner:'巴西', runnerUp:'瑞典', score:'5-2' },
    { year:1962, host:'智利', winner:'巴西', runnerUp:'捷克斯洛伐克', score:'3-1' },
    { year:1966, host:'英格兰', winner:'英格兰', runnerUp:'西德', score:'4-2' },
    { year:1970, host:'墨西哥', winner:'巴西', runnerUp:'意大利', score:'4-1' },
    { year:1974, host:'西德', winner:'西德', runnerUp:'荷兰', score:'2-1' },
    { year:1978, host:'阿根廷', winner:'阿根廷', runnerUp:'荷兰', score:'3-1' },
    { year:1982, host:'西班牙', winner:'意大利', runnerUp:'西德', score:'3-1' },
    { year:1986, host:'墨西哥', winner:'阿根廷', runnerUp:'西德', score:'3-2' },
    { year:1990, host:'意大利', winner:'西德', runnerUp:'阿根廷', score:'1-0' },
    { year:1994, host:'美国', winner:'巴西', runnerUp:'意大利', score:'0-0(3-2)' },
    { year:1998, host:'法国', winner:'法国', runnerUp:'巴西', score:'3-0' },
    { year:2002, host:'韩国/日本', winner:'巴西', runnerUp:'德国', score:'2-0' },
    { year:2006, host:'德国', winner:'意大利', runnerUp:'法国', score:'1-1(5-3)' },
    { year:2010, host:'南非', winner:'西班牙', runnerUp:'荷兰', score:'1-0' },
    { year:2014, host:'巴西', winner:'德国', runnerUp:'阿根廷', score:'1-0' },
    { year:2018, host:'俄罗斯', winner:'法国', runnerUp:'克罗地亚', score:'4-2' },
    { year:2022, host:'卡塔尔', winner:'阿根廷', runnerUp:'法国', score:'3-3(4-2)' }
  ],
  playerStats: {
    goals: [
      { name:'Kylian Mbappé', team:'France', value:8, flag:'🇫🇷' },
      { name:'Lionel Messi', team:'Argentina', value:7, flag:'🇦🇷' },
      { name:'Olivier Giroud', team:'France', value:4, flag:'🇫🇷' },
      { name:'Julián Álvarez', team:'Argentina', value:4, flag:'🇦🇷' },
      { name:'Marcus Rashford', team:'England', value:3, flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
      { name:'Richarlison', team:'Brazil', value:3, flag:'🇧🇷' },
      { name:'Bukayo Saka', team:'England', value:3, flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
      { name:'Enner Valencia', team:'Ecuador', value:3, flag:'🇪🇨' },
      { name:'Gonçalo Ramos', team:'Portugal', value:3, flag:'🇵🇹' },
      { name:'Cody Gakpo', team:'Netherlands', value:3, flag:'🇳🇱' }
    ],
    assists: [
      { name:'Lionel Messi', team:'Argentina', value:5, flag:'🇦🇷' },
      { name:'Antoine Griezmann', team:'France', value:4, flag:'🇫🇷' },
      { name:'Ivan Perišić', team:'Croatia', value:3, flag:'🇭🇷' },
      { name:'Harry Kane', team:'England', value:3, flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
      { name:'Kevin De Bruyne', team:'Belgium', value:3, flag:'🇧🇪' },
      { name:'Bruno Fernandes', team:'Portugal', value:3, flag:'🇵🇹' },
      { name:'Vinícius Jr', team:'Brazil', value:2, flag:'🇧🇷' },
      { name:'Jude Bellingham', team:'England', value:2, flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
      { name:'Kylian Mbappé', team:'France', value:2, flag:'🇫🇷' },
      { name:'Christian Eriksen', team:'Denmark', value:2, flag:'🇩🇰' }
    ],
    possession: [
      { name:'Spain', zh:'西班牙', flag:'🇪🇸', value:72.1 },
      { name:'Germany', zh:'德国', flag:'🇩🇪', value:68.5 },
      { name:'France', zh:'法国', flag:'🇫🇷', value:67.3 },
      { name:'Argentina', zh:'阿根廷', flag:'🇦🇷', value:66.8 },
      { name:'Brazil', zh:'巴西', flag:'🇧🇷', value:65.2 },
      { name:'England', zh:'英格兰', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', value:64.7 },
      { name:'Netherlands', zh:'荷兰', flag:'🇳🇱', value:63.9 },
      { name:'Portugal', zh:'葡萄牙', flag:'🇵🇹', value:62.4 },
      { name:'Belgium', zh:'比利时', flag:'🇧🇪', value:61.8 },
      { name:'Germany', zh:'德国', flag:'🇩🇪', value:60.5 }
    ],
    teamGoals: [
      { name:'France', zh:'法国', flag:'🇫🇷', value:16 },
      { name:'Argentina', zh:'阿根廷', flag:'🇦🇷', value:15 },
      { name:'England', zh:'英格兰', flag:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', value:13 },
      { name:'Brazil', zh:'巴西', flag:'🇧🇷', value:12 },
      { name:'Portugal', zh:'葡萄牙', flag:'🇵🇹', value:12 },
      { name:'Netherlands', zh:'荷兰', flag:'🇳🇱', value:10 },
      { name:'Spain', zh:'西班牙', flag:'🇪🇸', value:11 },
      { name:'Germany', zh:'德国', flag:'🇩🇪', value:9 },
      { name:'Croatia', zh:'克罗地亚', flag:'🇭🇷', value:8 },
      { name:'Belgium', zh:'比利时', flag:'🇧🇪', value:7 }
    ]
  }
};

/* Initialize match results from real data */
function initMatchResults() {
  const r = {};
  /* Real schedule + scores from FIFA API */
  const schedule = {
    A: [
      { home:'Mexico', away:'SouthAfrica', homeScore:2, awayScore:0, played:true },
      { home:'SouthKorea', away:'Czechia', homeScore:2, awayScore:1, played:true },
      { home:'Czechia', away:'SouthAfrica', homeScore:0, awayScore:0, played:false },
      { home:'Mexico', away:'SouthKorea', homeScore:0, awayScore:0, played:false },
      { home:'SouthAfrica', away:'SouthKorea', homeScore:0, awayScore:0, played:false },
      { home:'Czechia', away:'Mexico', homeScore:0, awayScore:0, played:false }
    ],
    B: [
      { home:'Canada', away:'Bosnia', homeScore:0, awayScore:0, played:false },
      { home:'Qatar', away:'Switzerland', homeScore:0, awayScore:0, played:false },
      { home:'Switzerland', away:'Bosnia', homeScore:0, awayScore:0, played:false },
      { home:'Canada', away:'Qatar', homeScore:0, awayScore:0, played:false },
      { home:'Bosnia', away:'Qatar', homeScore:0, awayScore:0, played:false },
      { home:'Switzerland', away:'Canada', homeScore:0, awayScore:0, played:false }
    ],
    C: [
      { home:'Brazil', away:'Morocco', homeScore:0, awayScore:0, played:false },
      { home:'Haiti', away:'Scotland', homeScore:0, awayScore:0, played:false },
      { home:'Scotland', away:'Morocco', homeScore:0, awayScore:0, played:false },
      { home:'Brazil', away:'Haiti', homeScore:0, awayScore:0, played:false },
      { home:'Morocco', away:'Haiti', homeScore:0, awayScore:0, played:false },
      { home:'Scotland', away:'Brazil', homeScore:0, awayScore:0, played:false }
    ],
    D: [
      { home:'USA', away:'Paraguay', homeScore:0, awayScore:0, played:false },
      { home:'Australia', away:'Turkiye', homeScore:0, awayScore:0, played:false },
      { home:'USA', away:'Australia', homeScore:0, awayScore:0, played:false },
      { home:'Turkiye', away:'Paraguay', homeScore:0, awayScore:0, played:false },
      { home:'Paraguay', away:'Australia', homeScore:0, awayScore:0, played:false },
      { home:'Turkiye', away:'USA', homeScore:0, awayScore:0, played:false }
    ],
    E: [
      { home:'Germany', away:'Curacao', homeScore:0, awayScore:0, played:false },
      { home:'IvoryCoast', away:'Ecuador', homeScore:0, awayScore:0, played:false },
      { home:'Germany', away:'IvoryCoast', homeScore:0, awayScore:0, played:false },
      { home:'Ecuador', away:'Curacao', homeScore:0, awayScore:0, played:false },
      { home:'Curacao', away:'IvoryCoast', homeScore:0, awayScore:0, played:false },
      { home:'Ecuador', away:'Germany', homeScore:0, awayScore:0, played:false }
    ],
    F: [
      { home:'Netherlands', away:'Japan', homeScore:0, awayScore:0, played:false },
      { home:'Sweden', away:'Tunisia', homeScore:0, awayScore:0, played:false },
      { home:'Netherlands', away:'Sweden', homeScore:0, awayScore:0, played:false },
      { home:'Tunisia', away:'Japan', homeScore:0, awayScore:0, played:false },
      { home:'Tunisia', away:'Netherlands', homeScore:0, awayScore:0, played:false },
      { home:'Japan', away:'Sweden', homeScore:0, awayScore:0, played:false }
    ],
    G: [
      { home:'Belgium', away:'Egypt', homeScore:0, awayScore:0, played:false },
      { home:'Iran', away:'NewZealand', homeScore:0, awayScore:0, played:false },
      { home:'Belgium', away:'Iran', homeScore:0, awayScore:0, played:false },
      { home:'NewZealand', away:'Egypt', homeScore:0, awayScore:0, played:false },
      { home:'NewZealand', away:'Belgium', homeScore:0, awayScore:0, played:false },
      { home:'Egypt', away:'Iran', homeScore:0, awayScore:0, played:false }
    ],
    H: [
      { home:'Spain', away:'CaboVerde', homeScore:0, awayScore:0, played:false },
      { home:'SaudiArabia', away:'Uruguay', homeScore:0, awayScore:0, played:false },
      { home:'Spain', away:'SaudiArabia', homeScore:0, awayScore:0, played:false },
      { home:'Uruguay', away:'CaboVerde', homeScore:0, awayScore:0, played:false },
      { home:'Uruguay', away:'Spain', homeScore:0, awayScore:0, played:false },
      { home:'CaboVerde', away:'SaudiArabia', homeScore:0, awayScore:0, played:false }
    ],
    I: [
      { home:'France', away:'Senegal', homeScore:0, awayScore:0, played:false },
      { home:'Iraq', away:'Norway', homeScore:0, awayScore:0, played:false },
      { home:'France', away:'Iraq', homeScore:0, awayScore:0, played:false },
      { home:'Norway', away:'Senegal', homeScore:0, awayScore:0, played:false },
      { home:'Senegal', away:'Iraq', homeScore:0, awayScore:0, played:false },
      { home:'Norway', away:'France', homeScore:0, awayScore:0, played:false }
    ],
    J: [
      { home:'Argentina', away:'Algeria', homeScore:0, awayScore:0, played:false },
      { home:'Austria', away:'Jordan', homeScore:0, awayScore:0, played:false },
      { home:'Argentina', away:'Austria', homeScore:0, awayScore:0, played:false },
      { home:'Jordan', away:'Algeria', homeScore:0, awayScore:0, played:false },
      { home:'Algeria', away:'Austria', homeScore:0, awayScore:0, played:false },
      { home:'Jordan', away:'Argentina', homeScore:0, awayScore:0, played:false }
    ],
    K: [
      { home:'Portugal', away:'CongoDR', homeScore:0, awayScore:0, played:false },
      { home:'Uzbekistan', away:'Colombia', homeScore:0, awayScore:0, played:false },
      { home:'Portugal', away:'Uzbekistan', homeScore:0, awayScore:0, played:false },
      { home:'Colombia', away:'CongoDR', homeScore:0, awayScore:0, played:false },
      { home:'CongoDR', away:'Uzbekistan', homeScore:0, awayScore:0, played:false },
      { home:'Colombia', away:'Portugal', homeScore:0, awayScore:0, played:false }
    ],
    L: [
      { home:'England', away:'Croatia', homeScore:0, awayScore:0, played:false },
      { home:'Ghana', away:'Panama', homeScore:0, awayScore:0, played:false },
      { home:'England', away:'Ghana', homeScore:0, awayScore:0, played:false },
      { home:'Panama', away:'Croatia', homeScore:0, awayScore:0, played:false },
      { home:'Panama', away:'England', homeScore:0, awayScore:0, played:false },
      { home:'Croatia', away:'Ghana', homeScore:0, awayScore:0, played:false }
    ]
  };
  for (const gid of Object.keys(schedule)) {
    r[gid] = schedule[gid];
  }
  __WC_DATA.matchResults = r;
}
initMatchResults();
